---
 - name: Install ans start the databases and web server
   yum:
     name:
       - "{{ ansible_local.custom.packeges.db_package }}"
       - "{{ ansible_local.custom.packeges.web_package }}"
     state: latest
 - name: Start the database service
   service:
     name: 
       - "{{ ansible_local.custom.services.db_service }}"
     state: started
     enabled: true
 - name: Start the httpd service
   service:
     name:
       - "{{ ansible_local.custom.services.web_service }}"
     state: started
     enabled: true
